apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-01-02T18:38:54Z"
  name: netology
  namespace: default
  resourceVersion: "375877"
  uid: b50c3955-a499-437a-a248-3f38a42daad4
